### ISSUE TITLE
Context finish event should dispatch finish events to child contexts

### ISSUE THREAD

**Issue by mikenerone** [asphalt-framework/asphalt#10]
I'm still wrapping my head around asphalt (but I love it so far, thank you!), so please forgive me if I'm misunderstanding the intent. The specific issue I ran into was this: I have a bunch of subcontexts for a bunch of HTTP requests to different places (not gratuitously - there are several components associated with each context, each connected to a signal on the previous component in the chain). When I CTRL-C the app, asyncio would complain about the unclosed responses. I added an event receiver method on my response object and connected it to the subcontext's finish signal. When I realized this didn't work, investigation turned up that there's no finish event dispatched in the subcontexts.

Having learned that, the workaround is trivial - I'm using `ctx.parent.finish.connect` for the moment, and it works, but I think this need for the component to know how deep it is in the subcontext tree goes against the portability/resuability I think you intend for these discrete components.

The approach that seems natural to me is for finish events to be, in effect, passed down to child contexts, recursively. I _think_ it would be appropriate to do so in general, and not just for app shutdown, since the inheritance from parent contexts might be broken if child contexts are allowed to continue without the parent context.

If there's a better approach I'm supposed to be using, please do let me know. Thanks again for an awesome framework.

**Comment by agronholm** [comment]
If you're finishing a parent context without finishing subcontext then it's likely you're doing something wrong. If you can, use `async with ChildContextClass(parent) as ctx: ...`. This will guarantee that the finish callbacks are unconditionally called when the block is exited.

Can you point me to the relevant piece of code?

**Comment by mikenerone** [comment]
Under normal operation, I would always finish child contexts before their parents. The specific case I'm talking about is something like a CTRL-C, where the user is demanding the application exit "now". `asphalt.core.run_application()` catches the `KeyboardInterrupt` and notifies only the root context. For shutdown to work properly (from the bottom up), that signal needs to propagate down to child contexts.

The real code is proprietary, here is an _extremely_ trivialized example (more tailored to illustrating this than to reflecting my actual practices):

```
class ApplicationComponent(ContainerComponent):

    async def start(self, ctx):
        ... # Do some setup stuff
        for source in ['a', 'b', 'c']:
            self.add_component('intake_{}'.format(source), LongPollerComponent, source=source)

        ############# Thanks to asphalt.core.run_application, this fires on CTRL-C #############
        @ctx.finished.connect
        def cleanup(event):
            ... # Do some app-level cleanup stuff


class IntakeComponent(ContainerComponent):

    async def start(self, ctx, source):
        subctx = Context(parent=ctx)  # So separate contexts are shared for components handling each source.
        ... # Do some setup stuff
        self.add_component('poller', LongPollerComponent, source=source)
        self.add_component('response_processor', ResponseProcessorComponent, source=source)

        ############# This also fires because we connected through the parent context. #############
        @ctx.finished.connect
        def cleanup(event):
            ... # Do some intaek-level cleanup stuff, I dunno :P


class LongPollerComponent(Component):

    response_events = Signal(ResponseEvent)  # I'll leave this class definition out. :)

    async def start(self, ctx):
        ctx.publish_resource(self.response_events, context_attr='response_events')
        connection = open_some_connection()
        task = asyncio.ensure_future(something_that_dispatches_response_event_occasionally(ctx, connection))

        ############# But this never fires because it connected on a subcontext. #############
        ############# It doesn't know it's a subcontext and shouldn't have to.   #############
        @ctx.finished.connect
        def cleanup(event):
            connection.close()
            task.cancel()


class ResponseProcessorComponent(Component):

    async def start(self, ctx):
        ... # Do some setup stuff

        ############# And this also never fires for the same reason. #############
        @ctx.finished.connect
        def cleanup(event):
            ... # Do some cleanup stuff

        for response_event in ctx.response_events.stream_events():
            ... # Do something
```
Now, I realize I could add a line to `IntakeComponent` that forwards the `finished` event down to the subcontext, but what I'm saying is that in general (IMO), all child contexts should receive that notification, so it should be part of the built-in plumbing provided by asphalt. Handling such plumbing for you (by which I mean me) is what makes frameworks like asphalt so useful. All it would really take is for the `Context` constructor to connect an event-forwarding method to the parent's `finished` signal.

**Comment by agronholm** [comment]
But the finished signal is only a _notification_ of shutdown, not something that actually shuts anything down automatically. Suppose you have a request being processed in a task running in a subcontext. If the subcontext is shut down before the task is finished, any service cleanup (like SQLAlchemy's session `close()`) is done prematurely, before the task has had a chance to finish up (it might catch CancelledError to perform its own cleanup).

**Comment by mikenerone** [comment]
> ...any tasks belonging to a subcontext must be finished before its subcontext is shut down.

Cascading the signal is what would allow that to happen. As it is now, after the root-level `finished` event is processed, `run_application()` rudely closes the event loop without sensitive subcomponents such as you mentioned ever having a chance to prepare for a clean shutdown (resulting in many log messages regarding open connections and such if you have asyncio in debug mode).

Although I think you might be saying that I am misunderstanding the intended semantics of the finished signal. My conclusion that the `finished` signal should _trigger_ shutdown activities is based on the example at http://asphalt.readthedocs.io/en/latest/tutorials/webnotifier.html, the salient portion of which is effectively:

```
class ChangeDetectorComponent(Component):
    async def start(self, ctx):
        def shutdown(event):
            task.cancel()
        ctx.finished.connect(shutdown)
        task = get_event_loop().create_task(...)
```
...which looks to me like, "Oh, I got a finished signal," (which in this case would only be caused by external termination), "so I'm going to cancel my long-lived task(s) so I can GTFO". :P But even if the signal is simply a notification that "Your work is done", then application exit seems like a pretty clear case of telling _all_ contexts "Your work is done", because it better be.

Let me just ask your intent, instead, though: what is the intended way for my subcontexts and/or subcomponents to find out that the user hit CTRL-C, for example?

**Comment by agronholm** [comment]
Closing of the parent context may not indicate that all tasks have been cancelled. Otherwise, simply adding a done callback to the task would suffice.

I am still not sure whether cancelling all the tasks right off the bat is the right thing to do. In the absence of  real world Asphalt applications I find that hard to determine.

**Comment by mikenerone** [comment]
If your modified `LongPollerComponent` is passed a subcontext, though (that's still what we're talking about, right?), then since that finished signal still never fires, the extra care you take in the cleanup function is for naught. So my question would still be simply, "How are [all the things] intended to find out that someone pressed CTRL-C?" (or similar action)?

> As an aside, are you really installing signals in components?

No, I was just doing everything I could think of to shorten my example. That's a big part of what I was referring to when I said it was "more tailored to illustrating this than to reflecting my actual practices." Although I will admit to a bit of confusion along the way due to the doc examples. For example, in the aforementioned tutorial, I'm still a little bothered by the infinite loop in `ApplicationComponent.start()`.

Anyways, I've enjoyed the discussion. Thanks much for your time. I'll keep my finished-forwarding workarounds in place for now - they work for this particular app, at least (feel free to close the issue unless you have further thoughts). Please keep the above question in mind as maintenance proceeds on asphalt. I love it!

**Comment by agronholm** [comment]
Under what circumstances would you pass the LongPollerComponent a subcontext?
Setting up the cleanup chain is the responsibility of whatever creates the subcontext.

**Comment by mikenerone** [comment]
My example is such a circumstance. There are n LongPollerComponents, each paired with one of n ResponseProcessorComponents. Each pair has a subcontext of their own, independent from those of other pairs. This ensures that there's no interaction between separate pairs, and allows the code to be simpler because within each separate subcontext, they can use identical resource names, for example. I constructed this example thinking it was a textbook case of why you'd use subcontexts. Please let me know if I've misapprehended something.

**Comment by agronholm** [comment]
I have a hard time commenting on your application's structure because I'm missing the big picture. How do they use the (sub)context? Why is isolation important in this case? Can you show me the code of `start()` in `IntakeComponent`? I desperately need real world examples from other people so I can re-evaluate my design.

**Comment by mikenerone** [comment]
Oh, I need to explain something about my app that got left out by oversimplifying: Please imagine that each LongPollerComponent loads a class (and spawn a task from it) that is determined at runtime based on a configuration file - in fact, each LongPollerComponent may load a totally different class with entirely different cleanup needs. The IntakeComponent above all this has no idea what those cleanup needs might be. This is why I have to get the finished event all the way down to the leaf contexts so that _each_ of those bottom class's cleanup methods can be triggered. I already have it doing this via workarounds.

I might be able to get permission for you to see the app code since I would just as much welcome your input on it. I don't have time to pursue that for at least a couple of weeks, though, so this kind of explanation is the best I can do for now.

**Comment by agronholm** [comment]
We both seem to agree at least that the finished signal needs to be propagated all the way down. What we disagree on is whether this should be automatic. If it's automatic, the code that manages the subcontext has no control over when and how the subcontext's finish callbacks are run. That is my primary concern here.

**Comment by mikenerone** [comment]
Ah, I misunderstood what we disagree on! I do see your concern. You're saying yes, send the signal down, but that the developer needs to be able to be granular in selecting the right point in the program flow to do so - quite possibly somewhere in the middle of the flow of a parent cleanup function. I'm feeling convinced. :P

**Comment by mikenerone** [comment]
I'm closing this as I've come around to complete agreement. Thanks for the consideration.

**Comment by agronholm** [comment]
@mikenerone I'm planning a much better solution for this now. Your feedback would be most welcome on issue #16.
