### ISSUE TITLE
container component error in docs?

### ISSUE THREAD

**Issue by petri** [asphalt-framework/asphalt#20]
The [example](http://asphalt.readthedocs.io/en/latest/tutorials/webnotifier.html#sending-changes-via-email) imports `ContainerComponent` but does not seem to do anything with it. Should it be used as the base class for the `ApplicationComponent`?

**Comment by agronholm** [comment]
Good catch. The examples used to be based on `ContainerComponent` and the import is a left over from that. I'll fix this real soon.
