### ISSUE TITLE
Require base type of resource

### ISSUE THREAD

**Issue by davidbrochart** [asphalt-framework/asphalt#44]
Great project!

I was wondering if it's possible to require a resource with a base type of the added resource, e.g. if I add this resource:
```py
class MyResource(BaseResource):
    ...
```
I would like to require it like this:
```py
class MyComponent(Component):

    @inject
    async def start(
        self,
        ctx: Context,
        *,
        my_resource: BaseResource = resource("my_resource"),
    ) -> None:
        ...
```
But it seems to require the exact type:
```
asphalt.core.context.ResourceNotFound: no matching resource was found for type=__main__.BaseResource name='my_resource'
```

**Comment by agronholm** [comment]
Yes, it requires an exact type, to avoid name clashes. If you really want this, add the resource with its base type like `types=[MyResource, BaseResource]`.
