### ISSUE TITLE
Configuration through the command line

### ISSUE THREAD

**Issue by davidbrochart** [asphalt-framework/asphalt#49]
Asphalt can currently be configured through YAML files, but it would be great to also support configuration through CLI arguments and options, that would take precedence over YAML files.

**Comment by agronholm** [comment]
Can you describe your use case and your suggestion in greater detail?

**Comment by davidbrochart** [comment]
Instead of writing a YAML file, or to modify an existing one, it is easier to pass some configuration directly at the command line if one wants to override it.
I'd like to point to a component like this:
```
asphalt run --path.to.my.component.arg="my_value" config0.yaml config1.yaml
```

**Comment by agronholm** [comment]
Something like `--set path.to.my.component.arg=my_value` would likely work better with `click`, but I get you. Do you have a specific use case where you need this?

**Comment by davidbrochart** [comment]
I will likely need it in [jpterm](https://github.com/davidbrochart/jpterm).

**Comment by davidbrochart** [comment]
I don't know if it would be easier with [typer](https://github.com/tiangolo/typer)?

**Comment by agronholm** [comment]
Would it? Typer itself is based on click.
