### ISSUE TITLE
Allow the use of overriding configuration files

### ISSUE THREAD

**Issue by agronholm** [asphalt-framework/asphalt#9]
The CLI should be able to accept an arbitary number of configuration files which would then override settings in each other. Alternatively, there could be an `.override.yaml` file, like how docker-compose does.

**Comment by mikenerone** [comment]
Haven't tested it, but the docs sound very much like [it already does that](http://asphalt.readthedocs.io/en/latest/userguide/deployment.html#running-the-asphalt-launcher).

**Comment by mikenerone** [comment]
Seems like this can be closed, as you added the feature already in 641b74659d1620b2cfbcc3a5c88353e29f42f79b.

**Comment by agronholm** [comment]
Yes indeed, I just forgot to close this issue.
